---

# Rewrite of the main file - configure_cci.rb. Due to the way prompts work or argument handling
# i used the set_fact in to set the arguemnts passed to variables.

# The extra variables will need to be passed in via the 'vars' folder



# Setting the variables in order to be used for the ssh commands
  tasks:
    #set_fact:
    # remoteIP: "{{ ip }}"
    # setPlan: "{{plan}}"
    #setIqn: "{{ iqn }}"
    # setUsername: "{{ username }}"
    # setPassword: "{{ password }}"
    # setTargetIp: "{{targetIp}}"
    #  setLicense: "{{license}}"
    #  setOra: "{{ora}}"

    - name: Transfer setup files
      shell: scp -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./setup_files/db2hosted.tar.gz root@{{ ip }}:/tmp

   	- name: expand the setup files
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"tar xvfz /tmp/db2hosted.tar.gz -C /tmp\"

    - name: setup network rules
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/sqldb-db2-hosted-boot-new ;/tmp/sqldb-db2-hosted-boot-new >> /tmp/sqldb-db2-hosted-boot-new.out \"

    - name: setup kernel parameters
    - shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/sqldb-setup-CentOS-new ;/tmp/sqldb-setup-CentOS-new >> /tmp/sqldb-setup-CentOS-new.out \" 

    - name: setup the san disk
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/sqldb-prepare-SAN-disks-new ;/tmp/sqldb-prepare-SAN-disks-new >> /tmp/sqldb-prepare-SAN-disks-new.out \" 

    - name: setup iscsi
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/sqldb-setup-iSCSI-new ; /tmp/sqldb-setup-iSCSI-new  {{ iqn }} {{ username }} {{ password }} {{ targetIp }} >> /tmp/sqldb-setup-iSCSI-new.out \" 

    - name: install db2
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/sqldb-install-DB2-new ;/tmp/sqldb-install-DB2-new {{ license }} {{ plan }} {{ ora }}} >> /tmp/sqldb-install-DB2-new.out \" 

    - name: run validation
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/validate_procurement.sh ;/tmp/validate_procurement.sh >> /tmp/validate_procurement.out  {{ plan }} \" 

    - name: create user and check for validation errors
      shell: ssh -i ~/.ssh/db2hosted-devops_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{{ ip }} \"chmod 0744 /tmp/create_user_cleanup.sh ;/tmp/create_user_cleanup.sh >> /tmp/create_user_cleanup.out \" 









